name: Calling Slack
run-name: Mentioning Teams in Slack based on the TriagerX recommendation

on:
  issue_comment:
    types: [created]

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    if: github.event.comment.user.login == 'github-actions[bot]' && contains(github.event.comment.body, 'Recommended Components:')  
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Make a request to the Slack server
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const axios = require('axios');

            const commentBody = github.event.comment.body;
            const components = commentBody.split('Recommended Components:')[1].split('\n')[0].trim().split(', ');
            
            console.log(components);

            // for every component, send a message to the corresponding slack channel
            // tell the developers in the channel that the issue with number <n> needs to be reviewed
            

